######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 28 17:41:27 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += camShift.h camshiftkalman.h LBP.h marco.h test.h util.h
SOURCES += camshiftkalman.cpp LBP.cpp main.cpp test.cpp util.cpp
